-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 19:55:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema control_ambiental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema control_ambiental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control_ambiental` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `control_ambiental` ;

-- -----------------------------------------------------
-- Table `control_ambiental`.`dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_ambiental`.`dispositivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_sensor` VARCHAR(100) NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT '1',
  `fecha_instalacion` DATE NULL DEFAULT NULL,
  `ultima_revision` DATE NULL DEFAULT NULL,
  `firmware_version` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `control_ambiental`.`alertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_ambiental`.`alertas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dispositivo_id` INT NULL DEFAULT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_alerta` VARCHAR(50) NULL DEFAULT NULL,
  `nivel_co2` FLOAT NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `dispositivo_id` (`dispositivo_id` ASC) VISIBLE,
  CONSTRAINT `alertas_ibfk_1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `control_ambiental`.`dispositivos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `control_ambiental`.`estado_de_bateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_ambiental`.`estado_de_bateria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dispositivo_id` INT NULL DEFAULT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `nivel_bateria` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `dispositivo_id` (`dispositivo_id` ASC) VISIBLE,
  CONSTRAINT `estado_de_bateria_ibfk_1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `control_ambiental`.`dispositivos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `control_ambiental`.`eventos_extractor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_ambiental`.`eventos_extractor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dispositivo_id` INT NULL DEFAULT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `accion` VARCHAR(10) NULL DEFAULT NULL,
  `co2_ppm` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `dispositivo_id` (`dispositivo_id` ASC) VISIBLE,
  CONSTRAINT `eventos_extractor_ibfk_1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `control_ambiental`.`dispositivos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `control_ambiental`.`lecturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_ambiental`.`lecturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dispositivo_id` INT NULL DEFAULT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `co2_ppm` FLOAT NULL DEFAULT NULL,
  `temperatura` FLOAT NULL DEFAULT NULL,
  `humedad` FLOAT NULL DEFAULT NULL,
  `nivel_bateria` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `dispositivo_id` (`dispositivo_id` ASC) VISIBLE,
  CONSTRAINT `lecturas_ibfk_1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `control_ambiental`.`dispositivos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
